"""
The sequence of triangle numbers is generated by adding the natural numbers

What is the value of the first triangle number to have over five hundred divisors?
"""
from util.tools import factors


def pe12():
    triangle = 0
    i = 2
    while True:
        triangle = sum(range(i))
        divisors = factors(triangle, edges=True)
        if len(divisors) > 500:
            break
        i += 1
    print(triangle)

if __name__ == '__main__':
    pe12()
