"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""

def fibonacci_gen():
    """
    A generator for Fibonacci numbers

    Yields:
        (int): Next Fibonacci number
    """
    f0 = 1
    f1 = 1
    while True:
        yield f1
        f1, f0 = f0 + f1, f1


def pe_2(max_val: int):
    res = 0
    for f in fibonacci_gen():
        if f <= max_val:
            if not f % 2:
                res += f
        else:
            break
    print(res)


if __name__ == "__main__":
    pe_2(4_000_000)
